### PR TITLE
Reuse matrix helpers from `@eng-automation/testing`

### PR DESCRIPTION
**Pull request by rzadp**

### CODE REVIEW

**Comment by rzadp** [comment]
Running into some weird issues with `yarn install` with this.

**Comment by mutantcornholio** [comment]
@rzadp well, one way around it is to remove `yarn.lock`

**Comment by Bullrich** [comment]
We can also make eng-automation work both with es modules and with ES2020 for every case

**Comment by rzadp** [comment]
> @rzadp well, one way around it is to remove `yarn.lock`

It helped locally, but not on CI 🤔

**Review by mutantcornholio — APPROVED** [review]

**Pull request merged**
