### PR TITLE
Added markup code generation

### LINKED ISSUE #277: Add structured data to generate organic trafic
From @mordamax's [comment](https://github.com/paritytech/polkadot-testnet-faucet/pull/274#discussion_r1206775159):

> I admit it could be irrelevant for us and this page right now, but just wanted to leave this idea here
> 
> We could potentially benefit some organic traffic by adding Structured Data snippet for FAQ section
> https://developers.google.com/search/docs/appearance/structured-data/faqpage
> 
> Not sure though if there's a need

### PR DESCRIPTION
**Pull request by Bullrich**
It generates a JSON object inside the header following the instructions from: https://developers.google.com/search/docs/appearance/structured-data/faqpage

It parses the information of the markdown text to generate this json object.

This resolves #277

### CODE REVIEW

**Comment by Bullrich** [comment]
<details><summary>Example JSON object</summary>

```json
{
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
        {
            "@type": "Question",
            "name": "## What is this?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>This is a polkadot-testnet faucet. You can use this to load testnet tokens into your account.</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## What is a faucet?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>A faucet is a developer tool to get a small amount of testnet tokens (ROC) in order to test and troubleshoot a decentralized application or protocol before going live on Polkadot, where one must use real DOT.<br/>Most faucets require social authentication (e.g. Twitter post or login confirming you are a real human) or place you in a queue to wait for a testnet token through the faucet. The Polkadot faucet is free, fast, and does not require authentication.</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## How do I use this?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>To request funds, simply enter your Rococo wallet address, fill the captcha, and hit \"Submit\".</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## How much ROC will I receive?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>You will receive 100 ROC per request.</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## How often can I request tokens?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>You can request tokens every 24h! If you request ROC for one account, you can't request more for another parachain in that period.</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## Can I request tokens for a specific parachain?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Yes, you can! To do so, click on \"Use custom chain id\" and then add the ID of your parachain. You can also load the site with the parachain selected by adding the GET parameter to the site \"?parachain=1001\".<br/>If you want to learn more about Parachains, check out [the docs](https://polkadot.network/features/parachains)!</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## What is a testnet token?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>Testnet tokens are a test currency that allows you to test your Polkadot application before going live. Testnet tokens can be used in place of real tokens on testnets like Rococo.<br/>You can read more [here](https://polkadot.network/blog/rococo-v1-a-holiday-gift-to-the-polkadot-community/).</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## Can I get real DOTs?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>No, we will provide you with TEST DOTs, so you can do your testing and move it to any parachain whenever you are ready</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## It worked! How can I say thank you?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>You can star the repository in [GitHub](https://github.com/paritytech/substrate-matrix-faucet).</p>"
            }
        },
        {
            "@type": "Question",
            "name": "## What if I run into any other issues, or have questions?",
            "acceptedAnswer": {
                "@type": "Answer",
                "text": "<p>You can [report an issue](https://github.com/paritytech/substrate-matrix-faucet/issues) in our repository or [ask in the forum](https://forum.polkadot.network/t/experiencing-trouble-accessing-our-rococo-faucet-please-post-here/2952)!</p>"
            }
        }
    ]
}
```
</details>

**Comment by Bullrich** [comment]
@mutantcornholio can you please help me with the linter?

I have **no idea** why it could be failing. I also don't know how to disable it for that line.

**Review by mordamax — APPROVED** [review]

**Comment by mutantcornholio** [comment]
> @mutantcornholio can you please help me with the linter?
> 
> I have **no idea** why it could be failling. I also don't know how to disable it for that line.

I think the issue might be coming from having `</script>` in the text block... 
I was able to go around it with defining a helper function in a separate `.ts` file:
```ts
export const serializeLd = (faqHeader: string): string => 
  `<script type="application/ld+json">${faqHeader}</script>`;
```
and then doing this:
```ts
<!-- eslint-disable svelte/no-at-html-tags -->
<svelte:head>
  {@html serializeLd(faqHeader)}
</svelte:head>
```
Note that `no-at-html-tags` rule is also triggered, and I guess the only way to go about it is disabling

**Comment by Bullrich** [comment]
> > @mutantcornholio can you please help me with the linter?
> > I have **no idea** why it could be failling. I also don't know how to disable it for that line.
> 
> I think the issue might be coming from having `</script>` in the text block... I was able to go around it with defining a helper function in a separate `.ts` file:
> 
> ```ts
> export const serializeLd = (faqHeader: string): string => 
>   `<script type="application/ld+json">${faqHeader}</script>`;
> ```
> 
> and then doing this:
> 
> ```svelte
> 
> <svelte:head>
>   {@html serializeLd(faqHeader)}
> </svelte:head>
> ```
> 
> Note that `no-at-html-tags` rule is also triggered, and I guess the only way to go about it is disabling

It works! That's amazing!

Thanks for your help @mutantcornholio

**Pull request merged**
